In [1]:
import sys
import numpy as np

print(f'System {sys.version}')
print(f'NumPy: {np.__version__}')

System 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy: 1.14.3


In [2]:
# defining a vector

x=np.array([1,2,3])

In [7]:
# vector dimensions and size
x.shape, x.size

((3, 3), 9)

In [5]:
# defining a matrix
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
# matrix dimension and size
x.shape, x.size

((3, 3), 9)

In [8]:
# define a matrix of given dimensions
x = np.ones((10,10))
# matrix dimension and size
x.shape, x.size

((10, 10), 100)

In [9]:
# 3d tensors
# define a matrix of given dimensions
x = np.ones((10,10,10))
# matrix dimension and size
x.shape, x.size

((10, 10, 10), 1000)

In [10]:
# indexing
x = np.ones((5,5), dtype=np.int)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
# assigning a single value
x[0,1] = 2
x

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
# assigning an entire row/column
x[:,2] = 3
x

array([[1, 2, 3, 1, 1],
       [1, 1, 3, 1, 1],
       [1, 1, 3, 1, 1],
       [1, 1, 3, 1, 1],
       [1, 1, 3, 1, 1]])

In [15]:
x[3,:]=5
x

array([[1, 2, 3, 1, 1],
       [1, 1, 3, 1, 1],
       [1, 1, 3, 1, 1],
       [5, 5, 5, 5, 5],
       [1, 1, 3, 1, 1]])

In [21]:
# indexing multidimentsional tensor
x = np.ones((5,5,5))
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [22]:
x[3,0,0] = 6
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[6., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [25]:
### matrix operations
x = np.matrix([[1,2],[3,4]])
y = np.ones((2,2), dtype=np.int)

In [26]:
# elementwise sum
x+y

matrix([[2, 3],
        [4, 5]])

In [27]:
# elementwise substraction
x-y

matrix([[0, 1],
        [2, 3]])

In [28]:
# multiplication
x*y

matrix([[3, 3],
        [7, 7]])

In [36]:
# matrix reshape
x = np.arange(10)
x = x.reshape((2,5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
# matrix transpose
x.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [38]:
# transpose of the transpose
x.T.T

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
# tensor
x = np.ones((3,3,3,3,3,3,3,3,3,3))
x.shape, x.size

((3, 3, 3, 3, 3, 3, 3, 3, 3, 3), 59049)